### ISSUE TITLE
[Problem] Find by tag (skill?)

### ISSUE THREAD

**Issue by simontegg** [holodex/app#83] opened 2015-05-28 10:21 UTC
As as user I want to find all the people that have a skill / are located in an area etc

**Comment by ahdinosaur** [comment] 2015-05-31 23:38
duplicate of https://github.com/open-app/holodex/issues/40, not sure which one to keep until we resolve https://github.com/holodex/app/issues/84.

**Closed as completed** 2016-08-02 03:49 UTC
Labels: needs-design
